### PR TITLE
Math magicians: events

### PR DESCRIPTION
**Pull request by Elhambasir**
### What is done in this PR ?

1. Create a new directory called `logic` inside your project
2. Copy the files `calculate.js` and `operate.js` 
3. Install [big.js](https://www.npmjs.com/package/big.js) into the `logic/` directory using NPM
5. Import `calculate.js` in your `Calculator.js` component
6. Implement click event handlers using the math logic from `calculate.js` and `operate.js` in the React component. The goal is to make all calculator buttons work according to their functionality e.g. the - button should subtract a given value.

This PR is raised to implement the following features: 👍 

- [x]  User can do simple calculations like add, multiply, divide, and subtract.

### How should it be tested?

**Clone the repository**
```javascript
git clone https://github.com/Elhambasir/math-magician.git
``` 

**Navigate to the folder**
```javascript
 cd math-magician
``` 

**Checkout the branch**
```javascript
 git checkout events
``` 

**Finally run this:**
```javascript
run npm start
``` 
If you face this error : ['react-scripts' is not recognized as an internal or external command]

**Please run this command:**
```javascript
npm install react-scripts --save-dev
``` 

Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by zieeco — APPROVED** [review]
# status: APPROVED :green_circle: :100: 

Hi, @Elhambasir, 




Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
*Your design could be improved by increasing the font size to improve the user experience*

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Elhambasir** [comment]
Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.

> # status: APPROVED 🟢 💯
> Hi, @Elhambasir,
> 
>  [ 68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966 ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966) [ ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966)
> 
> Good job so far 👍 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights ⚡
> ✅ Descriptive PR 👍 ✅ Nice design 🔥 ✅ Linters are passing 👏
> 
> ## Optional suggestions
> _Your design could be improved by increasing the font size to improve the user experience_
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you 

> # status: APPROVED 🟢 💯
> Hi, @Elhambasir,
> 
>  [ 68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966 ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966) [ ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966)
> 
> Good job so far 👍 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights ⚡
> ✅ Descriptive PR 👍 ✅ Nice design 🔥 ✅ Linters are passing 👏
> 
> ## Optional suggestions
> _Your design could be improved by increasing the font size to improve the user experience_
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @zieeco

**Comment by Elhambasir** [comment]
> # status: APPROVED 🟢 💯
> Hi, @Elhambasir,
> 
>  [ 68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966 ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966) [ ](https://camo.githubusercontent.com/8c280357dea8e7e1781e5ff938a2fe78281e09d8b2d2a5d21ccec391a36d6c43/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436d39774b6d4b4d556c525076646f4867552f67697068792d646f776e73697a65642d6d656469756d2e676966)
> 
> Good job so far 👍 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights ⚡
> ✅ Descriptive PR 👍 ✅ Nice design 🔥 ✅ Linters are passing 👏
> 
> ## Optional suggestions
> _Your design could be improved by increasing the font size to improve the user experience_
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @zieeco

**Comment by Elhambasir** [comment]
Thank you @zieeco

**Pull request merged**
